apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: {{ .Values.amiID }}   # AMI ID for worker nodes
  role: {{ .Values.karpenterNodeRole}}   # IAM role for worker nodes
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

    --==MYBOUNDARY==
    Content-Type: application/node.eks.aws

    ---
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      cluster:
        name: {{ .Values.clusterName }}
        apiServerEndpoint: {{ .Values.clusterEndpoint }}
        certificateAuthority: {{ .Values.clusterCA }}
        cidr: {{ .Values.clusterServiceCIDR }}
      kubelet:
        config:
          clusterDNS:
            - ${cidrhost({{ .Values.clusterServiceCIDR }}, 10)}
        flags:
        - --node-labels=karpenter.sh/controller=true

    --==MYBOUNDARY==
    Content-Type: text/x-shellscript

    #!/bin/bash
    /usr/bin/nodeadm init

    cat /proc/swaps
    sudo touch /etc/systemd/zram-generator.conf
    sudo swapoff -a

    if systemctl list-unit-files | grep -q '^firewalld'; then
      systemctl stop firewalld
      systemctl disable firewalld
    fi

    systemctl restart containerd

    # wait for containerd to be ready before restarting kubelet
    for i in {1..30}; do
      if systemctl is-active --quiet containerd; then
        echo "containerd is active"
        break
      fi
      echo "Waiting for containerd to be ready..."
      sleep 2
    done

    systemctl restart kubelet

    --==MYBOUNDARY==--

  tags:
    karpenter.sh/discovery: {{ .Values.clusterName }}
