karpenterNodeRole: ''
clusterName: ''
service_ipv4_cidr: ''
certificate_authority_data: ''
AWSAccountID: ''
karpenterControllerNodeName: 'karpenter-controller-nodes'
KarpenterWorkerNodeName: 'karpenter-worker-nodes'
amiID: 'ami-xxxxxxxx' # AMI ID for worker nodes, you can find the latest AL2023 AMI ID for your region from AWS documentation or console