apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{{ .Values.AWSAccountID }}:role/{{ .Values.karpenterControllerNodeName }}-role
      username: system:node:{{`{{EC2PrivateDNSName}}`}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::{{ .Values.AWSAccountID }}:role/{{ .Values.KarpenterWorkerNodeName }}-role
      username: system:node:{{`{{EC2PrivateDNSName}}`}}
      groups:
        - system:bootstrappers
        - system:nodes
