# This workflow is triggered manually via workflow_dispatch and performs Terraform initialization, 
# planning, validation, and either applies or destroys infrastructure based on user input. 
# It uses OIDC for secure AWS credential management and has permissions set for various GitHub Actions features.

name: Terraform Apply or Destroy
run-name: "🚀 Terraform Plan Apply or Destroy • Branch: ${{ github.ref }} • Job #${{ github.run_number }}"
on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to run'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
permissions:
  id-token: write  # Allow GitHub Actions to request OIDC tokens
  contents: write  # Allow GitHub Actions to read repository contents (e.g., for checkout)
  pull-requests: write  # Allow GitHub Actions to manage pull requests (e.g., for commenting on PRs with Terraform plan results)
  security-events: write  # Allow GitHub Actions to manage security events
  actions: write  # Allow GitHub Actions to manage actions
  checks: write  # Allow GitHub Actions to manage checks

jobs:
  terraform-pipeline:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        audience: sts.amazonaws.com
        aws-region: ap-south-1
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

    - name: Terraform Init
      run: terraform init -backend-config=environments/dev/backend-dev-us-east-1.tfvars

    - name: Terraform Plan
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform plan -out=tfplan -var-file=environments/dev/dev-us-east-1.tfvars

    - name: Terraform Validate
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform validate

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan
    
    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve